#!/bin/bash

set -e

if hash pyenv 2>/dev/null;
then
    echo "using pyenv wrapper"
    pyenv install --skip-existing
    pyenv exec pyvenv env
else
    echo "using pyvenv-3.4 (Built in python)"
    pyvenv-3.4 env
fi

env/bin/pip install -r requirements.txt